### ISSUE TITLE
Doxygen - Files do not have pages

### ISSUE THREAD

**Issue by joshSi** [Arkrissym/Discord.CPP#10]
**Describe the bug**

Was looking through the [documentation](https://arkrissym.github.io/Discord.CPP) and noticed that most of the files, I think all files that begin with a capital letter (i.e. `Activity.h`, `Activity.cpp`) do not have pages and will lead to a 404. The only one I could reach was [static.h](https://arkrissym.github.io/Discord.CPP/static_8h.html) / [static.cpp](https://arkrissym.github.io/Discord.CPP/static_8cpp.html)

**To Reproduce**

Go to https://arkrissym.github.io/Discord.CPP and try to access docs on a file

**Expected behavior**

**Screenshots**

https://user-images.githubusercontent.com/19968417/234736144-881acae9-a5d0-4587-8ae5-4b563892cd1a.mov

https://user-images.githubusercontent.com/19968417/234736165-ee0566d9-091e-4ea3-8723-fc37648bf6dc.mov

**Environment**
 - OS

 - Versions of dependencies

**Additional context**

**Comment by Arkrissym** [comment]
Thanks for the report. Fixed with 182d7775bc35980247a5572052d90b3992875856
