### ISSUE TITLE
reciving op code 9

### ISSUE THREAD

**Issue by koftrciali** [Arkrissym/Discord.CPP#8]
i start the test_bot project it says Identify payload has been sent
then i recive only op code 9

**Expected behavior**
session to be valid

**Environment**
 - OS WINDOWS 10
 - Version [e.g. 22] discord api verison 6
 - all dependices are dowlanded at 28.02.2022 (including boost)

**LOGS**
DEBUG - Thread-3792 - discord.object.request_internal - sending message  via GET to https://discord.com/api/v6/gateway/bot
DEBUG - Thread-3792 - discord.object.request_internal - response: 200: {"url": "wss://gateway.discord.gg", "shards": 1, "session_start_limit": {"total": 1000, "remaining": 980, "reset_after": 82450547, "max_concurrency": 1}}
DEBUG - Thread-3792 - discord.object.api_call - caching object
DEBUG - Threadpool-0-Thread-0 - Worker - Thread started
DEBUG - Threadpool-0-Thread-1 - Worker - Thread started
DEBUG - Threadpool-0-Thread-2 - Worker - Thread started
DEBUG - Threadpool-0-Thread-3 - Worker - Thread started
INFO - Thread-3792 - discord - connecting to websocket: wss://gateway.discord.gg?v=6&encoding=json&compress=zlib-stream
DEBUG - Threadpool-0-Thread-0 - Discord.MainGateway (shard id: [0, 1]) - host: gateway.discord.gg               query: /?v=6&encoding=json&compress=zlib-stream
INFO - Threadpool-0-Thread-0 - Discord.MainGateway (shard id: [0, 1]) - connecting to websocket: wss://gateway.discord.gg?v=6&encoding=json&compress=zlib-stream
INFO - Threadpool-0-Thread-0 - Discord.MainGateway (shard id: [0, 1]) - Successfully connected to endpoint: 162.159.130.234:443
DEBUG - Threadpool-0-Thread-2 - Discord.MainGateway (shard id: [0, 1]) - Starting message reveiving loop.
DEBUG - Threadpool-0-Thread-2 - Discord.MainGateway (shard id: [0, 1]) - Received 114 bytes
DEBUG - Threadpool-0-Thread-2 - Discord.MainGateway (shard id: [0, 1]) - Received message: {"t":null,"s":null,"op":10,"d":{"heartbeat_interval":41250,"_trace":["[\"gateway-prd-us-east1-b-nkrj\",{\"micros\":0.0}]"]}}
DEBUG - Threadpool-0-Thread-3 - Discord.MainGateway (shard id: [0, 1]) - set heartbeat_interval: 41250
DEBUG - Threadpool-0-Thread-0 - Discord.MainGateway (shard id: [0, 1]) - sending message: {"d":{"intents":23175,"large_threshold":250,"properties":{"$browser":"Discord.C++","$device":"Discord.C++","$os":"Windows"},"shard":[0,1],"token":"MTA4MDIwMjg4Mjg2OTEwODg3Nw.G-9dPg.9igRKxaEjvJvA9z5aTdiS-ziXQaA0Uh8RUILsA"},"op":2}
DEBUG - Threadpool-0-Thread-0 - Discord.MainGateway (shard id: [0, 1]) - Message sent: {"d":{"intents":23175,"large_threshold":250,"properties":{"$browser":"Discord.C++","$device":"Discord.C++","$os":"Windows"},"shard":[0,1],"token":"MTA4MDIwMjg4Mjg2OTEwODg3Nw.G-9dPg.9igRKxaEjvJvA9z5aTdiS-ziXQaA0Uh8RUILsA"},"op":2}
INFO - Threadpool-0-Thread-3 - Discord.MainGateway (shard id: [0, 1]) - Identify payload has been sent
DEBUG - Threadpool-0-Thread-1 - Discord.MainGateway (shard id: [0, 1]) - sending message: {"d":"null","op":1}
DEBUG - Threadpool-0-Thread-1 - Discord.MainGateway (shard id: [0, 1]) - Message sent: {"d":"null","op":1}
DEBUG - Heartbeat-Thread-0 - Discord.MainGateway (shard id: [0, 1]) - Heartbeat message has been sent
DEBUG - Threadpool-0-Thread-2 - Discord.MainGateway (shard id: [0, 1]) - Received 0 bytes
INFO - Threadpool-0-Thread-2 - Discord.MainGateway (shard id: [0, 1]) - Websocket connection closed
INFO - Threadpool-0-Thread-2 - Discord.MainGateway (shard id: [0, 1]) - trying to reconnect in 0.000000s
DEBUG - Threadpool-0-Thread-3 - Discord.MainGateway (shard id: [0, 1]) - host: gateway.discord.gg               query: /?v=6&encoding=json&compress=zlib-stream
INFO - Threadpool-0-Thread-3 - Discord.MainGateway (shard id: [0, 1]) - connecting to websocket: wss://gateway.discord.gg?v=6&encoding=json&compress=zlib-stream
INFO - Threadpool-0-Thread-3 - Discord.MainGateway (shard id: [0, 1]) - Successfully connected to endpoint: 162.159.130.234:443
DEBUG - Threadpool-0-Thread-0 - Discord.MainGateway (shard id: [0, 1]) - Starting message reveiving loop.
INFO - Threadpool-0-Thread-2 - Discord.MainGateway (shard id: [0, 1]) - reconnected
DEBUG - Threadpool-0-Thread-0 - Discord.MainGateway (shard id: [0, 1]) - Received 114 bytes
DEBUG - Threadpool-0-Thread-0 - Discord.MainGateway (shard id: [0, 1]) - Received message: {"t":null,"s":null,"op":10,"d":{"heartbeat_interval":41250,"_trace":["[\"gateway-prd-us-east1-d-rplf\",{\"micros\":0.0}]"]}}
DEBUG - Threadpool-0-Thread-3 - Discord.MainGateway (shard id: [0, 1]) - set heartbeat_interval: 41250
DEBUG - Threadpool-0-Thread-1 - Discord.MainGateway (shard id: [0, 1]) - sending message: {"d":{"intents":23175,"large_threshold":250,"properties":{"$browser":"Discord.C++","$device":"Discord.C++","$os":"Windows"},"shard":[0,1],"token":"MTA4MDIwMjg4Mjg2OTEwODg3Nw.G-9dPg.9igRKxaEjvJvA9z5aTdiS-ziXQaA0Uh8RUILsA"},"op":2}
DEBUG - Threadpool-0-Thread-1 - Discord.MainGateway (shard id: [0, 1]) - Message sent: {"d":{"intents":23175,"large_threshold":250,"properties":{"$browser":"Discord.C++","$device":"Discord.C++","$os":"Windows"},"shard":[0,1],"token":"MTA4MDIwMjg4Mjg2OTEwODg3Nw.G-9dPg.9igRKxaEjvJvA9z5aTdiS-ziXQaA0Uh8RUILsA"},"op":2}
INFO - Threadpool-0-Thread-3 - Discord.MainGateway (shard id: [0, 1]) - Identify payload has been sent
DEBUG - Threadpool-0-Thread-0 - Discord.MainGateway (shard id: [0, 1]) - Received 0 bytes
INFO - Threadpool-0-Thread-0 - Discord.MainGateway (shard id: [0, 1]) - Websocket connection closed
INFO - Threadpool-0-Thread-2 - Discord.MainGateway (shard id: [0, 1]) - trying to reconnect in 0.000000s
DEBUG - Threadpool-0-Thread-1 - Discord.MainGateway (shard id: [0, 1]) - host: gateway.discord.gg               query: /?v=6&encoding=json&compress=zlib-stream
INFO - Threadpool-0-Thread-1 - Discord.MainGateway (shard id: [0, 1]) - connecting to websocket: wss://gateway.discord.gg?v=6&encoding=json&compress=zlib-stream
INFO - Threadpool-0-Thread-1 - Discord.MainGateway (shard id: [0, 1]) - Successfully connected to endpoint: 162.159.130.234:443
DEBUG - Threadpool-0-Thread-0 - Discord.MainGateway (shard id: [0, 1]) - Starting message reveiving loop.
INFO - Threadpool-0-Thread-2 - Discord.MainGateway (shard id: [0, 1]) - reconnected
DEBUG - Threadpool-0-Thread-0 - Discord.MainGateway (shard id: [0, 1]) - Received 114 bytes
DEBUG - Threadpool-0-Thread-0 - Discord.MainGateway (shard id: [0, 1]) - Received message: {"t":null,"s":null,"op":10,"d":{"heartbeat_interval":41250,"_trace":["[\"gateway-prd-us-east1-b-xsd9\",{\"micros\":0.0}]"]}}
DEBUG - Threadpool-0-Thread-1 - Discord.MainGateway (shard id: [0, 1]) - set heartbeat_interval: 41250
DEBUG - Threadpool-0-Thread-3 - Discord.MainGateway (shard id: [0, 1]) - sending message: {"d":{"intents":23175,"large_threshold":250,"properties":{"$browser":"Discord.C++","$device":"Discord.C++","$os":"Windows"},"shard":[0,1],"token":"MTA4MDIwMjg4Mjg2OTEwODg3Nw.G-9dPg.9igRKxaEjvJvA9z5aTdiS-ziXQaA0Uh8RUILsA"},"op":2}
DEBUG - Threadpool-0-Thread-3 - Discord.MainGateway (shard id: [0, 1]) - Message sent: {"d":{"intents":23175,"large_threshold":250,"properties":{"$browser":"Discord.C++","$device":"Discord.C++","$os":"Windows"},"shard":[0,1],"token":"MTA4MDIwMjg4Mjg2OTEwODg3Nw.G-9dPg.9igRKxaEjvJvA9z5aTdiS-ziXQaA0Uh8RUILsA"},"op":2}
INFO - Threadpool-0-Thread-1 - Discord.MainGateway (shard id: [0, 1]) - Identify payload has been sent
DEBUG - Threadpool-0-Thread-0 - Discord.MainGateway (shard id: [0, 1]) - Received 19 bytes
DEBUG - Threadpool-0-Thread-0 - Discord.MainGateway (shard id: [0, 1]) - Received message: {"t":null,"s":null,"op":9,"d":false}

**Comment by Arkrissym** [comment]
First of all you should update the library, your version uses v6 API. Main branch is on v9 and development branch is on v10.

The issue is likely caused by the test_bot using privileged intents which you need to enable in your application's settings. In the "Bot" section check "Server Members Intent" and "Message Content Intent".

Also you need to regenerate your bot token. The debug logs contain the token.

**Comment by koftrciali** [comment]
my first time making bot.
ty you was right.
i checked "Server Members Intent" and "Message Content Intent"
